# Generated by Django 4.0.3 on 2022-03-22 20:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreApellidosResponsable', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('CuentaBancaria', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSociedad', models.CharField(max_length=255)),
                ('Cif', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('CuentaBancaria', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('NombreApellidos', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=255)),
                ('TelefonoContacto', models.CharField(max_length=255)),
                ('EmailContacto', models.CharField(max_length=255)),
                ('subdominio', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('UltimaCompra', models.DateField()),
                ('CosteCompraSinIva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('CosteCompraConIva', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Iva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Unidad', models.CharField(choices=[('1', 'Kilo'), ('2', 'Gramos'), ('3', 'Miligramos'), ('4', 'Litro'), ('5', 'Cl'), ('6', 'Unidades')], max_length=20)),
                ('Stock', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Naranja', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
                ('Rojo', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsCategorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Color', models.CharField(choices=[('1', 'Amarillo'), ('2', 'Naranja'), ('3', 'Rosa'), ('4', 'Rojo'), ('5', 'Morado'), ('6', 'Verde Agua'), ('7', 'Azul'), ('8', 'Azul Oscuro'), ('9', 'Verde'), ('10', 'Verde Oscuro'), ('11', 'Plateado'), ('12', 'Dorado')], max_length=255)),
                ('Icono', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('PrecioVentaSinIva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('PrecioVentaConIva', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Iva', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosCategorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Color', models.CharField(choices=[('1', 'Amarillo'), ('2', 'Naranja'), ('3', 'Rosa'), ('4', 'Rojo'), ('5', 'Morado'), ('6', 'Verde Agua'), ('7', 'Azul'), ('8', 'Azul Oscuro'), ('9', 'Verde'), ('10', 'Verde Oscuro'), ('11', 'Plateado'), ('12', 'Dorado')], max_length=255)),
                ('Icono', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TamanosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamano', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Familiar'), ('XXL', 'Gigante'), ('MR', 'Media Ración'), ('RE', 'Ración Entera'), ('T', 'Tapa'), ('N', 'Normal'), ('MON', 'Montadito')], max_length=26)),
                ('Cantidad_S', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_M', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_L', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_XL', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_XXL', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_MR', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_RE', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_T', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_N', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Cantidad_MON', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_S', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_M', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_L', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_XL', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_XXL', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_MR', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_RE', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_T', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_N', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('Perdida_MON', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_S', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_M', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_L', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_XL', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_XXL', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_MR', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_ME', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_T', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_N', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('TotalPerdida_MON', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_S', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_M', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_L', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_XL', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_XXL', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_MR', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_ME', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_T', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_N', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Coste_MON', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APP.items')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APP.productos')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.productoscategorias'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Componentes',
            field=models.ManyToManyField(through='APP.TamanosProductos', to='APP.items'),
        ),
        migrations.CreateModel(
            name='OwnerEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255, null=True)),
                ('DNI', models.CharField(max_length=255, null=True)),
                ('Telf', models.CharField(max_length=255, null=True)),
                ('Direccion', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('PASS', models.CharField(max_length=255, null=True)),
                ('Negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.itemscategorias'),
        ),
        migrations.AddField(
            model_name='items',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.proveedor'),
        ),
    ]
